---
sudo: false
language: python
python:
  - 3.7
  - 3.8
cache: pip
install:
  - pip install -e .
script:
  - bacolonyzer --help
before_deploy:
  - pip install mkdocs mkdocs-material
  - mkdocs build --verbose --clean --strict
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: site
    on:
      python: 3.7
      branch: master
