site_name: BaColonyzer
docs_dir: docs
site_dir: site

repo_name: "judithbergada/bacolonyzer"
repo_url: "https://github.com/judithbergada/bacolonyzer"
edit_uri: "tree/master/docs/"

# Google Analytics
google_analytics:
  - UA-139052696-2
  - auto

# Copyright
copyright: "Copyright &copy; 2019 Judith Bergadà Pijuan"

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Outputs: outputs.md
  - Algorithm: algorithm.md

theme:
  name: material
  logo: assets/bacteria.svg
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: green
    accent: indigo

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - codehilite
  - attr_list
  - pymdownx.arithmatex

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/judithbergada/bacolonyzer
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/j_bergada
